# Use lightweight OpenJDK image
FROM eclipse-temurin:21-jdk-jammy

# Set working directory
WORKDIR /app

# Copy the built JAR file from host to container
COPY target/*.jar app.jar

# JVM options (optional)
ENV JAVA_OPTS=""

# Expose Spring Boot default port
EXPOSE 8080

# Run the JAR
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
