# Use OpenJDK 21 base image
FROM eclipse-temurin:21-jdk-jammy

# Set working directory
WORKDIR /app

# Copy all project files (source code + pom.xml)
COPY . .

# Make mvnw executable if you're using Maven Wrapper
RUN chmod +x ./mvnw

# Expose Spring Boot port
EXPOSE 8080

# Start Spring Boot in dev mode
CMD ["./mvnw", "spring-boot:run"]
