spring:
  output:
    ansi:
      enabled: always

  flyway:
    baseline-on-migrate: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: pravinson222@gmail.com
    password: fbur wgum xipe wfkf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          protocol: smtp
          test-connection: false

  datasource:
    url: jdbc:postgresql://localhost:5432/jobportal_Db
    username: postgres
    password: 3333
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    debug: true

server:
  port: 8080
  error:
    include-stacktrace: always

cors:
  allowed-origins: http://localhost:3000
