spring:
  datasource:
    url: jdbc:postgresql://dpg-d13pr4ggjchc73feh7ng-a.frankfurt-postgres.render.com:5432/jobportal_db_2cy7
    username: jobportal_db_2cy7_user
    password: F1p2Yz1sN06Am8FNvPXkRcv5hf2a2DCq
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_email_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          protocol: smtp
          test-connection: false
    default-encoding: UTF-8
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  error:
    include-stacktrace: never

cors:
  allowed-origins: https://your-frontend.vercel.app

jwt:
  secret: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.pravin.job_portal_backend: DEBUG
