spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: codepravo@gmail.com
    password: frfw pqxt bhew qivf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

  devtools:
    add-properties: false

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://ep-super-bread-a4spskgp-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_wMyXHB2bcx6G
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-stacktrace: always
