spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_email_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          protocol: smtp
          test-connection: false
    default-encoding: UTF-8
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  error:
    include-stacktrace: never

logging:
  level:
    root: INFO
