services:
  - type: web
    name: job-portal-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d13pr4ggjchc73feh7ng-a.frankfurt-postgres.render.com:5432/jobportal_db_2cy7
      - key: DATABASE_USERNAME
        value: jobportal_db_2cy7_user
      - key: DATABASE_PASSWORD
        value: F1p2Yz1sN06Am8FNvPXkRcv5hf2a2DCq
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: your_email@gmail.com
      - key: MAIL_PASSWORD
        value: your_email_app_password
